### ISSUE TITLE
TimeAdjustmentsType

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#12]
## Acceptance criteria

- [x] It should have an `earlier:TimeAdjustment` #16 
- [x] It should have an `earliest:TimeAdjustment` #16
- [x] It should have a `later:TimeAdjustment` #16
- [x] It should have a `latest:TimeAdjustment` #16

## Schema

```graphql
type TflApiPresentationEntitiesJourneyPlannerTimeAdjustments {
  earlier: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment
  earliest: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment
  later: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment
  latest: TflApiPresentationEntitiesJourneyPlannerTimeAdjustment
}
```
