### ISSUE TITLE
DisruptionType

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#17]
## Acceptance criteria

- [x] It should have an `additionalInfo:String`
- [x] It should have an `affectedRoutes:[RouteSectionType]` #29 
- [x] It should have an `affectedStops:[StopPointType]` #27 
- [x] It should have a `category:Category` #43 
- [x] It should have a `categoryDescription: String`
- [x] It should have `closureText: String`
- [x] It should have a `created: String`
- [x] It should have a `description: String`
- [x] It should have a `lastUpdate: String`
- [x] It should have a `summary: String`
- [x] It should have a `type: String`

## Schema

```graphql
"""Represents a disruption to a route within the transport network."""
type TflApiPresentationEntitiesDisruption {
  """Gets or sets the additionaInfo of this disruption."""
  additionalInfo: String

  """Gets or sets the routes affected by this disruption"""
  affectedRoutes: [TflApiPresentationEntitiesRouteSection]

  """Gets or sets the stops affected by this disruption"""
  affectedStops: [TflApiPresentationEntitiesStopPoint]

  """Gets or sets the category of this dispruption."""
  category: Category

  """Gets or sets the description of the category."""
  categoryDescription: String

  """Text describing the closure type"""
  closureText: String

  """Gets or sets the date/time when this disruption was created."""
  created: String

  """Gets or sets the description of this disruption."""
  description: String

  """Gets or sets the date/time when this disruption was last updated."""
  lastUpdate: String

  """Gets or sets the summary of this disruption."""
  summary: String

  """Gets or sets the disruption type of this dispruption."""
  type: String
}
```
