### ISSUE TITLE
IdentifierType

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#36]
## Acceptance criteria

- [x] It should have a `crowding: CrowdingType` #13 
- [x] It should have a `fullName: String`
- [x] It should have an `id: String`
- [x] It should have a `name: String`
- [x] It should have a `routeType: RouteType` #37 
- [x] It should have a `status: Status` #42 
- [x] It should have a `type: String`
- [x] It should have a `uri: String`

## Schema

```graphql
type TflApiPresentationEntitiesIdentifier {
  crowding: TflApiPresentationEntitiesCrowding
  fullName: String
  id: String
  name: String
  routeType: RouteType
  status: Status
  type: String
  uri: String
}
```
