### ISSUE TITLE
JourneyLeg

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#4]
## Acceptance criteria

- [x] It should have an `arrivalPoint: Point` #49 
- [x] It should have an `arrivalTime: String`
- [x] It should have a `departurePoint: Point` #49 
- [x] It should have a `departureTime: String`
- [x] It should have a `disruptions: [Disruption]` #17 
- [x] It should have a `distance: Float`
- [x] It should have a `duration: Int`
- [x] It should have a `hasFixedLocations: Boolean`
- [x] It should have an `instruction: Instruction` #50 
- [x] It should have an `isDisrupted: Boolean`
- [x] It should have a `mode: Identifier`
- [x] It should have an `obstacles: [Obstacle]` #56 
- [x] It should have a `path: Path`
- [x] It should have a `plannedWorks: [PlannedWork]` #57
- [x] It should have a `routeOptions: [RouteOption]` #58
- [x] It should have a `speed: String`

## Schema

```graphql
type TflApiPresentationEntitiesJourneyPlannerLeg {
  """
  Represents a point located at a latitude and longitude using the WGS84 co-ordinate system.
  """
  arrivalPoint: TflApiPresentationEntitiesPoint
  arrivalTime: String

  """
  Represents a point located at a latitude and longitude using the WGS84 co-ordinate system.
  """
  departurePoint: TflApiPresentationEntitiesPoint
  departureTime: String
  disruptions: [TflApiPresentationEntitiesDisruption] #17 
  distance: Float
  duration: Int
  hasFixedLocations: Boolean
  instruction: TflApiPresentationEntitiesInstruction
  isDisrupted: Boolean
  mode: TflApiPresentationEntitiesIdentifier
  obstacles: [TflApiPresentationEntitiesJourneyPlannerObstacle]
  path: TflApiPresentationEntitiesJourneyPlannerPath
  plannedWorks: [TflApiPresentationEntitiesJourneyPlannerPlannedWork]
  routeOptions: [TflApiPresentationEntitiesJourneyPlannerRouteOption] 
  speed: String
}

```
