### ISSUE TITLE
InstructionStep

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#51]
## Acceptance criteria

- [x] It should have a `cumulativeDistance: Int`
- [x] It should have a `cumulativeTravelTime: Int`
- [x] It should have a `description: String`
- [x] It should have a `descriptionHeading: String`
- [x] It should have a `distance: Int`
- [x] It should have a `latitude: Float`
- [x] It should have a `longitude: Float`
- [x] It should have a `pathAttribute: PathAttribute` #52 
- [x] It should have a `skyDirection: Int`
- [x] It should have a `skyDirectionDescription: SkyDirectionDescription` #53
- [x] It should have a `streetName: String`
- [x] It should have a `trackType: TrackType` #54
- [x] It should have a `turnDirection: String`

## Schema
```graphql
type TflApiPresentationEntitiesInstructionStep {
  cumulativeDistance: Int
  cumulativeTravelTime: Int
  description: String
  descriptionHeading: String
  distance: Int
  latitude: Float
  longitude: Float
  pathAttribute: PathAttribute
  skyDirection: Int
  skyDirectionDescription: SkyDirectionDescription
  streetName: String
  trackType: TrackType
  turnDirection: String
}
```
