### ISSUE TITLE
ItineraryResultType

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#7]
## Acceptance criteria

- [x] It should have an String array of optional `stopMessages:[String]`
- [x] It should have a `recommendedMaxAgeMinutes:Int`
- [x] It should have an array of `lines: [LineType]` #8
- [x] It should have an array of `journeys: [JourneyPlannerJourneyType]` #9
- [x] It should have a `journeyVector: JourneyVectorType` #3 
- [x] It should have a `searchCriteria: SearchCriteria` #10 
- [x] It should have a `cycleHireDockingStationData: cycleHireDockingStationData` #11

## Schema

```graphql
"""A DTO representing a list of possible journeys."""
type TflApiPresentationEntitiesJourneyPlannerItineraryResult {
  cycleHireDockingStationData: TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData
  journeyVector: TflApiPresentationEntitiesJourneyPlannerJourneyVector
  journeys: [TflApiPresentationEntitiesJourneyPlannerJourney]
  lines: [TflApiPresentationEntitiesLine]
  recommendedMaxAgeMinutes: Int
  searchCriteria: TflApiPresentationEntitiesJourneyPlannerSearchCriteria
  stopMessages: [String]
}
```
