### ISSUE TITLE
LineType

### ISSUE THREAD

**Issue by mathewtrivett** [mathewtrivett/tfl-graph#8]
## Acceptance criteria

- [x] It should have a `created: String` 
- [x] It should have a `id: String`
- [x] It should have a `modeName: String`
- [x] It should have a `modified:String`
- [x] It should have a `name:String`
- [x] It should have a `crowding: CrowdingType` #13 
- [x] It should have a `disruptions: [DisruptionType]` #17 
- [x] It should have a `lineStatuses: [LineStatusType]` #18 
- [x] It should have a `routeSections: [MatchedRouteType]` #21 
- [x] It should have a `serviceTypes: [LineServiceTypeInfoType]` #22 

## Schema

```graphql
type TflApiPresentationEntitiesLine {
  created: String
  crowding: TflApiPresentationEntitiesCrowding
  disruptions: [TflApiPresentationEntitiesDisruption]
  id: String
  lineStatuses: [TflApiPresentationEntitiesLineStatus]
  modeName: String
  modified: String
  name: String
  routeSections: [TflApiPresentationEntitiesMatchedRoute]
  serviceTypes: [TflApiPresentationEntitiesLineServiceTypeInfo]
}
```
